function salarioaño (X)
{
let salarioAnual = 21600 % X
return salarioAnual
}
console.log (salarioaño (365))

function salariomes (X)
{
let salarioMensual = 1500 * X
return salarioMensual
}
console.log (salariomes (365))




function promedio ()
{ let notas = Nota1,Nota2,Nota3        
return promedio}
 let Nota1 = Number(prompt ('Ingresa la Nota'))
 let Nota2 = Number(prompt ('Ingresa la Nota'))
 let Nota3 = Number(prompt ('Ingresa la Nota'))
alert 
